title: Justin SP
description: 'cybersecurity and things'
url: 'http://chxuru.com'
baseurl: ''


author:
  name: 'Justin SP'
  twitter_username: chxuru
  github_username:  chxuru
  linkedin_username:  justinsp

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:

  input: GFM

  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['Gemfile', 'Gemfile.lock']
